#set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
#set_property PACKAGE_PIN A18 [get_ports {btn_in[3]}]
#set_property PACKAGE_PIN A19 [get_ports {btn_in[2]}]
#set_property PACKAGE_PIN A17 [get_ports {btn_in[1]}]
#set_property PACKAGE_PIN A10 [get_ports {btn_in[0]}]
#set_property PACKAGE_PIN N21 [get_ports uart_rxd]
#set_property PACKAGE_PIN M21 [get_ports uart_txd]

set_property PACKAGE_PIN D23 [get_ports clk100M_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk100M_in]
set_property PACKAGE_PIN L23 [get_ports rst_in]
set_property IOSTANDARD LVCMOS33 [get_ports rst_in]
set_property PACKAGE_PIN E11 [get_ports rstn_in]
set_property IOSTANDARD LVCMOS33 [get_ports rstn_in]

set_property PACKAGE_PIN D21 [get_ports tmds_clock_out_p]
set_property PACKAGE_PIN C22 [get_ports tmds_clock_out_n]

set_property PACKAGE_PIN A23 [get_ports tmds_data0_out_p]
set_property PACKAGE_PIN A24 [get_ports tmds_data0_out_n]

set_property PACKAGE_PIN C21 [get_ports tmds_data1_out_p]
set_property PACKAGE_PIN B21 [get_ports tmds_data1_out_n]

set_property PACKAGE_PIN B20 [get_ports tmds_data2_out_p]
set_property PACKAGE_PIN A20 [get_ports tmds_data2_out_n]
