set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
#set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property PACKAGE_PIN A18 [get_ports {btn_in[3]}]
set_property PACKAGE_PIN A19 [get_ports {btn_in[2]}]
set_property PACKAGE_PIN A17 [get_ports {btn_in[1]}]
set_property PACKAGE_PIN A10 [get_ports {btn_in[0]}]
#set_property PACKAGE_PIN N21 [get_ports uart_rxd]
#set_property PACKAGE_PIN M21 [get_ports uart_txd]

set_property PACKAGE_PIN D23 [get_ports clk100M_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk100M_in]
set_property PACKAGE_PIN L23 [get_ports rst_in]
set_property IOSTANDARD LVCMOS33 [get_ports rst_in]
#set_property PACKAGE_PIN E11 [get_ports rstn_in]
#set_property IOSTANDARD LVCMOS33 [get_ports rstn_in]

set_property PACKAGE_PIN D21 [get_ports tmds_clock_out_p]
set_property PACKAGE_PIN C22 [get_ports tmds_clock_out_n]

set_property PACKAGE_PIN A23 [get_ports tmds_data0_out_p]
set_property PACKAGE_PIN A24 [get_ports tmds_data0_out_n]

set_property PACKAGE_PIN C21 [get_ports tmds_data1_out_p]
set_property PACKAGE_PIN B21 [get_ports tmds_data1_out_n]

set_property PACKAGE_PIN B20 [get_ports tmds_data2_out_p]
set_property PACKAGE_PIN A20 [get_ports tmds_data2_out_n]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_7seg_out_tri_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_7seg_out_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_7seg_out_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_7seg_out_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_7seg_out_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_7seg_out_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_7seg_out_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_7seg_out_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_7seg_out_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_out_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_out_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_out_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_out_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_out_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_out_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_out_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_led_out_tri_o[0]}]
set_property PACKAGE_PIN F10 [get_ports {gpio_7seg_out_tri_o[8]}]
set_property PACKAGE_PIN G10 [get_ports {gpio_7seg_out_tri_o[7]}]
set_property PACKAGE_PIN C9 [get_ports {gpio_7seg_out_tri_o[6]}]
set_property PACKAGE_PIN G11 [get_ports {gpio_7seg_out_tri_o[5]}]
set_property PACKAGE_PIN E13 [get_ports {gpio_7seg_out_tri_o[4]}]
set_property PACKAGE_PIN D9 [get_ports {gpio_7seg_out_tri_o[3]}]
set_property PACKAGE_PIN B9 [get_ports {gpio_7seg_out_tri_o[2]}]
set_property PACKAGE_PIN E10 [get_ports {gpio_7seg_out_tri_o[1]}]
set_property PACKAGE_PIN D8 [get_ports {gpio_7seg_out_tri_o[0]}]
set_property PACKAGE_PIN E16 [get_ports {gpio_led_out_tri_o[0]}]
set_property PACKAGE_PIN C18 [get_ports {gpio_led_out_tri_o[7]}]
set_property PACKAGE_PIN D18 [get_ports {gpio_led_out_tri_o[6]}]
set_property PACKAGE_PIN C16 [get_ports {gpio_led_out_tri_o[5]}]
set_property PACKAGE_PIN D15 [get_ports {gpio_led_out_tri_o[4]}]
set_property PACKAGE_PIN C14 [get_ports {gpio_led_out_tri_o[3]}]
set_property PACKAGE_PIN F19 [get_ports {gpio_led_out_tri_o[2]}]
set_property PACKAGE_PIN E17 [get_ports {gpio_led_out_tri_o[1]}]

set_property PACKAGE_PIN D11 [get_ports {gpio_7seg_out_tri_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_7seg_out_tri_o[9]}]
